### ISSUE TITLE
Feedback requested on object storage scheme

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Swift#1]
It can be found in [the wiki](https://github.com/crkn-rcdr/CIHM-Swift/wiki/Access-Object-Storage-scheme).

@RussellMcOrmond: let me know if I'm missing any expected results of how Smelter will be dividing things up. I also decided to create "metadata" and "image" containers under an "access" account, which seems a bit painfully obvious at the moment. Are we deciding that this is the fundamental source of truth for all "access" images and metadata? Do we need to finally come up with a name for the access platform? Will other metadata formats end up living here as well?

**Comment by RussellMcOrmond** [comment]
I think this plus JSON in CouchDB will be the source of truth.  Swift will be so much cleaner for the types of things we currently put as attachments in CouchDB.  I suspect there will still be thing where couch is the better place to have as that source.

Yes, we use MARC and DC for Series.

I remain uncomfortable associating the OCR data with a canvas as it generated in relation to an image.  We may have to do transformations of that data to map positional information into canvas annotation, which means it isn't sourced as canvas metadata.   In the simple case we handle at this early stage they may seem equivalent, but they aren't once we start to do more interesting things with our canvases.  Having the OCR PDF and OCR XML using the same noid seems appropriate as they together represents the full OCR metadata.

The OCR PDF files need to be stored, and I didn't see reference to those files. We will source these for generating manifest sequenced multi-page PDF files for download, as well as allowing individual page PDF downloads.  Not sure what your thinking is of where these access-platform derivatives should be stored.

Some OCR data will come from the preservation platform, and some will come directly into the access platform.  We'll want to ensure we include in the design a way to load that OCR data directly and make the right associations with the images that were OCR'd (no longer represented in METS if this is done separate from the preservation platform).

As well as source images and derivative OCR, we have some born digital PDFs which will need a place to be stored.  These are different from the page-level PDFs as the born digital are source files rather than derivative files.  We may need to derive other files from these sources (Such as individual page-level PDFs with their own identifiers to make generating manifests of PDF pages annotating canvases easier to represent).

We will want to decide what to do with the older concatenated PDF OCR files, and if we will want Smelter to split them up into individual single-page PDFs to make them similar to the more recently OCR'd images.

**Comment by SaschaAdler** [comment]
I'm reading the [IIIF Presentation API 3.0 Beta spec on Canvases](https://iiif.io/api/presentation/3.0/#53-canvas) and it actually seems like the solution to doing interesting things with canvases is to annotate canvases within other canvases:

> Canvases may be treated as content resources for the purposes of annotating on to other Canvases. For example, a Canvas (Canvas A) with a video resource and Annotations representing subtitles or captions may be annotated on to another Canvas (Canvas B). This pattern maintains the correct spatial and temporal alignment of Canvas A’s content relative to Canvas B’s dimensions.

(If I ever do another Access talk about this, I'm going to use the [Xzibit meme](https://knowyourmeme.com/memes/xzibit-yo-dawg).)

It seems like the viewer is supposed to be responsible for the math involved in transforming annotations from one canvas to the other. I have no idea what viewers support doing this at the moment, although since it isn't part of our immediate use case I don't think we need to worry about that just yet. What I do take from the IIIF presentation model is that all annotations are owned by canvases, and so if we associate OCR content with images directly and not with annotations, we'll have to do some data structure manipulation to get it to work with the presentation model. As such, I'm still in favour of associating OCR content with canvases themselves. If it seems like we might store multiple iterations of OCR metadata for a given canvas (e.g. when running OCR again on old stuff) we might need to treat OCR metadata as a first-level concept in the scheme and link the multiple iterations to the same canvas.

I've added a few things to the scheme:

* dmd: To reinforce that this is the ultimate source of truth, I've added parl.json on manifests, heritage.json on canvases, which completes all of our sources for descriptive metadata. When we have a better sense of what this data will look like in our new metadata application profile, I suspect these two (and perhaps even DC and issueinfo!) will be collected into one format.
* pdfs: I've combined images and PDFs into a "files" container. References to PDFs, like images, will be found in Couch. I do like the idea of splitting up concatenated OCR PDFs into single page ones, and then having some sensible process for generating manifest-level PDFs from single pages if necessary.

**Comment by RussellMcOrmond** [comment]
I think we are mixing a few things.

* How we store images and their derivatives in the Access platform, to help in organising and offering through our public APIs (directly from Swift, etc).
* How IIIF, and potentially other protocols, then reference them.


At the file storage level we should be thinking in terms of whether the file is publicly accessible or private (as that would require different Swift containers), and grouping together related files for easier file management.


Images and their derivatives are all annotations onto canvases in IIIF, but if images aren't stored as part of a canvas then why treat the derivative PDF and/or XML files differently?  I'm not sure why the XML would be separated from its related PDF file, as they are a pairing that together represent the output of the OCR process.  Neither the PDF or the XML are "annotations", but data from which annotations can be extracted We will likely later author tools to extract annotations from PDFs in the case that the XML doesn't exist.  We already do that for the search data for born digital PDFs.   Given Cantaloupe can offer image annotations from source image and PDF files, these files are closer to being canvas data than the XML file is.

If we store a IIIF related derivative data in Swift, then it makes sense to focus on how IIIF treats that material, although I suspect we'll instead be storing that in an annotations server.


BTW: OCR software takes images as input, not a canvas.  We don't need to use IIIF terminology outside the IIIF context.  I will be trying not to call a sequence of images and associated metadata in the access platform a structMap :-)

Re-concatenating PDF's:  There is a bubble in the roadmap for this, so we should assume someone will work on that once the first phase is complete :-) 

Have a great Canada Day long weekend!

**Comment by RussellMcOrmond** [comment]
Separate from the above (although it does suggest context):

I think we should do some additional thinking about what Swift containers to be putting things in.  https://github.com/crkn-rcdr/CIHM-Swift/wiki/Access-Object-Storage-scheme currently suggests /v1/access/metadata/ and /v1/access/files/ , but I don't know it is clear that all /metadata/ should be restricted and all /files/ should be available via anonymous read.

At the very least we want to have a container for things which will be offered directly for download to patrons, and things which are password restricted.

Currently we have https://github.com/crkn-rcdr/cihm-file-access for all file access, but we could use that (or something like it ) for access to file restricted by credentials, and directly reference Swift endpoints for files which can be downloaded by anonymous patrons.

Lets flip this around to what I see as the requirements of the Swift layout:

*  ACL's in Swift are per-container, so we want separate containers for files which will have different access control.  There is a API to generate a temporary URL for a file (URL expires after a time), so some files offered for download don't need to be in a container with a world readable ACL.
* Files within a container have identifiers from the same namespace, or that the namespace is contained within the name.  We want to be able to walk the file list and confirm association between files and related databases, carrying out garbage collection (or at least notifications for manual maintenance) if there are mismatches (files not referenced in database, database entries where the underlying file is missing).
* That any direct references to containers that patrons may make be clearly documented as ephemeral, as it might be subject to change (as our design needs change, etc).

**Comment by SaschaAdler** [comment]
More recent discussion on this can be found [in the Access-Platform repo](https://github.com/crkn-rcdr/Access-Platform/issues/4).
